### ISSUE TITLE
Question about Project2_solution

### ISSUE THREAD

**Issue by Hunterzhaoliu** [joanxiao/robotics#1]
Your edx projects for the robotics course are awesome and very concise. I have a question on your project2_solution solution.py file. I understood what you did up to the line when you rotate the x axis to be aligned with the object. Why did you make w negative? Thanks again.

**Comment by joanxiao** [comment]
Good question 

I believe that's because the rotation axis w is defined as np.cross(v_c_o, x_axis). If it's defined as np.cross(x_axis, v_c_o,), the negative sign won't be needed. You can take a look at the picture in [the wikipedia page](https://en.wikipedia.org/wiki/Cross_product) to gain intuitions.
